FROM python:3

USER root

RUN apt-get update && apt-get install && mkdir /code/

WORKDIR /code/

ARG CACHEBUST_REQ=1

COPY server/requirements.txt server/
RUN python3 -m pip install --no-cache-dir -r ./server/requirements.txt

ARG CACHEBUST_APP=1

COPY server/setup.py server/
COPY server/src/ server/src/
COPY server/client/templates server/client/templates

RUN pip install -e server

CMD app