FROM michaelgreendev_server

RUN python3 -m pip install pytest==6.2.1 pdbpp IPython \
    && echo "alias ipython from IPython import embed; embed()" > "/root/.pdbrc"

COPY server/client/static/ server/client/static/
COPY server/tests/ server/tests/