FROM michaelgreendev_blog

RUN python3 -m pip install pytest==6.2.1 pdbpp IPython \
    && echo "alias ipython from IPython import embed; embed()" > "/root/.pdbrc"

COPY blog/client/static/ blog/client/static/
COPY blog/tests/ blog/tests/